/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustCenterRouteImport } from './routes/trust-center'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SmartpocketRouteImport } from './routes/smartpocket'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as InvestorRelationsRouteImport } from './routes/investor-relations'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ForBanksRouteImport } from './routes/for-banks'
import { Route as EarlyAccessRouteImport } from './routes/early-access'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CareerApplyRouteImport } from './routes/career-apply'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TrustCenterRoute = TrustCenterRouteImport.update({
  id: '/trust-center',
  path: '/trust-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartpocketRoute = SmartpocketRouteImport.update({
  id: '/smartpocket',
  path: '/smartpocket',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorRelationsRoute = InvestorRelationsRouteImport.update({
  id: '/investor-relations',
  path: '/investor-relations',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBanksRoute = ForBanksRouteImport.update({
  id: '/for-banks',
  path: '/for-banks',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessRoute = EarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerApplyRoute = CareerApplyRouteImport.update({
  id: '/career-apply',
  path: '/career-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career-apply': typeof CareerApplyRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/early-access': typeof EarlyAccessRoute
  '/for-banks': typeof ForBanksRoute
  '/insights': typeof InsightsRoute
  '/investor-relations': typeof InvestorRelationsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smartpocket': typeof SmartpocketRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/trust-center': typeof TrustCenterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career-apply': typeof CareerApplyRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/early-access': typeof EarlyAccessRoute
  '/for-banks': typeof ForBanksRoute
  '/insights': typeof InsightsRoute
  '/investor-relations': typeof InvestorRelationsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smartpocket': typeof SmartpocketRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/trust-center': typeof TrustCenterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career-apply': typeof CareerApplyRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/early-access': typeof EarlyAccessRoute
  '/for-banks': typeof ForBanksRoute
  '/insights': typeof InsightsRoute
  '/investor-relations': typeof InvestorRelationsRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smartpocket': typeof SmartpocketRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/trust-center': typeof TrustCenterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/career-apply'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/early-access'
    | '/for-banks'
    | '/insights'
    | '/investor-relations'
    | '/privacy'
    | '/products'
    | '/sitemap.xml'
    | '/smartpocket'
    | '/solutions'
    | '/terms'
    | '/thank-you'
    | '/trust-center'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career-apply'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/early-access'
    | '/for-banks'
    | '/insights'
    | '/investor-relations'
    | '/privacy'
    | '/products'
    | '/sitemap.xml'
    | '/smartpocket'
    | '/solutions'
    | '/terms'
    | '/thank-you'
    | '/trust-center'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/career-apply'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/disclaimer'
    | '/early-access'
    | '/for-banks'
    | '/insights'
    | '/investor-relations'
    | '/privacy'
    | '/products'
    | '/sitemap.xml'
    | '/smartpocket'
    | '/solutions'
    | '/terms'
    | '/thank-you'
    | '/trust-center'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareerApplyRoute: typeof CareerApplyRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EarlyAccessRoute: typeof EarlyAccessRoute
  ForBanksRoute: typeof ForBanksRoute
  InsightsRoute: typeof InsightsRoute
  InvestorRelationsRoute: typeof InvestorRelationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmartpocketRoute: typeof SmartpocketRoute
  SolutionsRoute: typeof SolutionsRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  TrustCenterRoute: typeof TrustCenterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust-center': {
      id: '/trust-center'
      path: '/trust-center'
      fullPath: '/trust-center'
      preLoaderRoute: typeof TrustCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smartpocket': {
      id: '/smartpocket'
      path: '/smartpocket'
      fullPath: '/smartpocket'
      preLoaderRoute: typeof SmartpocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor-relations': {
      id: '/investor-relations'
      path: '/investor-relations'
      fullPath: '/investor-relations'
      preLoaderRoute: typeof InvestorRelationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-banks': {
      id: '/for-banks'
      path: '/for-banks'
      fullPath: '/for-banks'
      preLoaderRoute: typeof ForBanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access': {
      id: '/early-access'
      path: '/early-access'
      fullPath: '/early-access'
      preLoaderRoute: typeof EarlyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-apply': {
      id: '/career-apply'
      path: '/career-apply'
      fullPath: '/career-apply'
      preLoaderRoute: typeof CareerApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareerApplyRoute: CareerApplyRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DisclaimerRoute: DisclaimerRoute,
  EarlyAccessRoute: EarlyAccessRoute,
  ForBanksRoute: ForBanksRoute,
  InsightsRoute: InsightsRoute,
  InvestorRelationsRoute: InvestorRelationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmartpocketRoute: SmartpocketRoute,
  SolutionsRoute: SolutionsRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  TrustCenterRoute: TrustCenterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
